// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blpncntrxsvuxyvpboyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJscG5jbnRyeHN2dXh5dnBib3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTI3NzUsImV4cCI6MjA2NTQ4ODc3NX0.LcD06-xb7PHin48subFDbEnQNGi3FIaFQ8awu2hOSyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);